openapi: 3.0.1
info:
  title: go-deploy API
  description: This is the API explorer for the go-deploy API. You can use it as a
    reference for the API endpoints.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Support
    url: https://github.com/kthcloud/go-deploy
  license:
    name: MIT License
    url: https://github.com/kthcloud/go-deploy?tab=MIT-1-ov-file#readme
  version: "1.0"
servers:
- url: /
paths: {}
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-Api-Key
      in: header
x-original-swagger-version: "2.0"
