info:
  contact:
    name: Support
    url: https://github.com/kthcloud/go-deploy
  description: This is the API explorer for the go-deploy API. You can use it as a
    reference for the API endpoints.
  license:
    name: MIT License
    url: https://github.com/kthcloud/go-deploy?tab=MIT-1-ov-file#readme
  termsOfService: http://swagger.io/terms/
  title: go-deploy API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Api-Key
    type: apiKey
swagger: "2.0"
