externalUrl: deploy.localhost:32275
port: 8080
mode: dev

timer:
  gpuSynchronize: 5m
  gpuLeaseSynchronize: 15s
  vmStatusUpdate: 20s
  vmSnapshotUpdate: 30s
  deploymentStatusUpdate: 5s 
  deploymentPingUpdate: 15s
  snapshot: 1h
  deploymentRepair: 30m 
  vmRepair: 30m
  smRepair: 30m
  metricsUpdate: 1m 
  jobFetch: 1s
  failedJobFetch: 1s 
  deploymentDeletionConfirm: 5s 
  vmDeletionConfirm: 5s
  smDeletionConfirm: 5s
  customDomainConfirm: 30m

zones:
- name: local
  description: Local development zone
  k8s:
    namespaces:
      deployment: deploy
      vm: deploy-vms
      system: deploy-system
    configSource:
      type: localPath
      path: ./kube/go-deploy-dev.yml
    ingressNamespace: kube-system
  capabilities:
    - deployment
    - vm
  domains:
    parentDeployment: app.deploy.localhost:32275
    parentSm: storage.deploy.localhost:32275
    parentVm: vm.deploy.localhost:32275
    parentVmApp: vm-app.deploy.localhost:32275
  storage:
    nfsServer: 10.96.200.2
    paths:
      parentDeployment: /nfs/deployments
  portRange:
    start: 31401
    end: 31426

registry:
  url: localhost:31276
  placeholderImage: localhost:31276/library/go-deploy-placeholder
  vmHttpProxyImage: localhost:31276/library/go-deploy-placeholder

gpu:
  privilegedGpus:
  excludedHosts:
  excludedGpus:

deployment:
  defaultZone: local
  port: 8080
  prefix: deploy-
  wildcardCertSecretNamespace: cert-manager
  wildcardCertSecretName: go-deploy-wildcard-secret
  customDomainTxtRecordSubdomain: _kthcloud
  ingressClass: nginx
  resources:
    autoScale:
      cpuThreshold: 50
      memoryThreshold: 50
    limits:
      cpu: 0.2
      memory: 0.5
      storage: 1
    requests:
      cpu: 0.1
      memory: 0.1

vm:
  defaultZone: local
  adminSshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3ktpoOPJP6v79i3IyY2+vd5julRDLBrMLpCAe8d4UDH09BN9PLYRAeYbox1UcHH3G+qWuf6iIY5/oxhsZlEmCbJE1wr3rVHvutuP17mcXcdVdJlQ7QOsTqI9rUTFm8XUB83CGIC36rxada3q7ndr/RhpwUtVghYK8AT57NjUjR5PI6TayKBIqlxgzamPJPcklCWoFhMzMm/8C15J1FJTejBeLuLeC6y+jtlxUGO7WDsLRS68uzpGGiS9exDkABrnb7jSU8o6rzQpIJnipIoM75530MV3Lp7sxNEgp8psaETdyPorfPv7u1nCcQV9B3RhH3SLGqzcepwt9zXixxcniVokAYvHLzpxcRg6bSoqWvJHM97fe8hDwa36Jck6hdfSGDxVon49E1qfG4FB4JYwwX2ehnuc3zW/bP+VuwFC+Fr/9zJMXiSGKSnIQKrMWqWbUse3r7kzUCLJ3PACCjGRR74LmhPODzPv3Zc5sz5cGFzOR2bNgUEUB1NK0Cw7GaO8= emil@thinkpad
  image: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

roles:
  - name: default
    description: Default
    iamGroup: default
    permissions:
      chooseZone: false
      chooseGpu: false
      useCustomDomains: false
      useGpus: false
      usePrivilegedGpus: false
    quotas:
      cpuCores: 2
      ram: 4
      diskSize: 20
      snapshots: 1
      gpuLeaseDuration:
  - name: base
    description: base
    iamGroup: base
    permissions:
      chooseZone: false
      chooseGpu: false
      useCustomDomains: true
      useGpus: true
      usePrivilegedGpus: false
    quotas:
      cpuCores: 4
      ram: 16
      diskSize: 50
      snapshots: 5
      gpuLeaseDuration: 5
  - name: power
    description: power
    iamGroup: power
    permissions:
      chooseZone: true
      chooseGpu: true
      useCustomDomains: true
      useGpus: true
      usePrivilegedGpus: true
    quotas:
      cpuCores: 40
      ram: 160
      diskSize: 2000
      snapshots: 10
      gpuLeaseDuration: 168

keycloak:
  url: http://keycloak.deploy.localhost:31125
  realm: master
  adminGroup: admin
  storageClient:
    clientId: go-deploy-storage
    clientSecret: YyPyCOQ2qoU9Vh8EgA87HO30rOJkoAdH

mongodb:
  url: mongodb://admin:admin@localhost:31536
  name: deploy

redis:
  url: localhost:30702
  password: 

sys-api:
  url: 
  user: 
  password: 
  clientId: 
  useMock: true

harbor:
  url: http://harbor.deploy.localhost:31276
  user: admin
  password: Harbor12345
  webhookSecret: secret
