externalUrl: http://localhost:8080
port: 8080
mode: dev

timer:
  deploymentStatusUpdate: 30s
  deploymentPingUpdate: 15s
  deploymentDeletionConfirm: 5s
  deploymentRepair: 30m

  smDeletionConfirm: 5s
  smRepair: 30m

  vmStatusUpdate: 30s
  vmDeletionConfirm: 5s
  vmRepair: 30m

  gpuSynchronize: 5m
  gpuLeaseSynchronize: 15s

  metricsUpdate: 1m
  customDomainConfirm: 30m
  staleResourceCleanup: 1h

  jobFetch: 1s
  failedJobFetch: 1s

zones:
- name: local
  enabled: true
  description: Local development zone
  k8s:
    namespaces:
      deployment: deploy
      vm: deploy-vms
      system: deploy-system
    configSource:
      type: localPath
      path: ./kube/go-deploy-dev.yml
    ingressNamespace: kube-system
  capabilities:
    - deployment
    - vm
  domains:
    parentDeployment: app.deploy.localhost:30091
    parentSm: storage.deploy.localhost:30091
    parentVm: vm.deploy.localhost
    parentVmApp: vm-app.deploy.localhost:30091
  storage:
    nfsServer: 10.96.200.2
    paths:
      parentDeployment: /nfs/deployments
  portRange:
    start: 31860
    end: 31885

registry:
  url: localhost:31007
  placeholderImage: localhost:31007/library/go-deploy-placeholder
  vmHttpProxyImage: localhost:31007/library/go-deploy-placeholder

gpu:
  privilegedGpus:
  excludedHosts:
  excludedGpus:

deployment:
  defaultZone: local
  port: 8080
  lifetime: 2160h # 90d
  prefix: deploy-
  fallback:
    disabled:
        name: deploy-fallback

  wildcardCertSecretNamespace: cert-manager
  wildcardCertSecretName: go-deploy-wildcard-secret
  customDomainTxtRecordSubdomain: _kthcloud

  ingressClass: nginx

  resources:
    autoScale:
      cpuThreshold: 50
      memoryThreshold: 50
    limits:
      cpu: 0.2
      memory: 0.5
      storage: 1
    requests:
      cpu: 0.1
      memory: 0.1

vm:
  defaultZone: local
  lifetime: 2160h # 90d
  adminSshPublicKey: 
  image: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

roles:
  - name: default
    description: Default
    iamGroup: default
    permissions:
      chooseZone: false
      chooseGpu: false
      useCustomDomains: false
      useGpus: false
      usePrivilegedGpus: false
    quotas:
      cpuCores: 2
      ram: 4
      diskSize: 20
      gpuLeaseDuration:
  - name: base
    description: base
    iamGroup: base
    permissions:
      chooseZone: false
      chooseGpu: false
      useCustomDomains: true
      useGpus: true
      usePrivilegedGpus: false
    quotas:
      cpuCores: 4
      ram: 16
      diskSize: 50
      gpuLeaseDuration: 5
  - name: power
    description: power
    iamGroup: power
    permissions:
      chooseZone: true
      chooseGpu: true
      useCustomDomains: true
      useGpus: true
      usePrivilegedGpus: true
    quotas:
      cpuCores: 40
      ram: 160
      diskSize: 2000
      snapshots: 10
      gpuLeaseDuration: 168

keycloak:
  url: http://keycloak.deploy.localhost:31001
  realm: master
  adminGroup: admin
  storageClient:
    clientId: go-deploy-storage
    clientSecret: U77Vm8MPPrW7ULj5GQnxMmlIBDLE5jTu

mongodb:
  url: mongodb://admin:admin@localhost:30508
  name: deploy

redis:
  url: localhost:32349
  password: 

sys-api:
  url: 
  user: 
  password: 
  clientId: 
  useMock: true

harbor:
  url: http://harbor.deploy.localhost:31007
  user: admin
  password: Harbor12345
  webhookSecret: secret
