---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-deploy-api
  namespace: landing
  labels:
    app.kubernetes.io/name: go-deploy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-deploy-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-deploy-api
    spec:
      containers:
        - name: go-deploy-api
          image: registry.cloud.cbh.kth.se/system/go-deploy-api
          envFrom:
            - configMapRef:
                name: go-deploy-api-config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: system-ci-secret
      restartPolicy: Always
