---
apiVersion: v1
kind: Service
metadata:
  name: go-deploy-api
  namespace: landing
  labels:
    app.kubernetes.io/name: go-deploy-api
spec:
  ports:
    - name: http-go-deploy-api
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: go-deploy-api