# https://github.com/goharbor/harbor-helm
# externalURL: "http://harbor.deploy.localhost:9080"
# Setting up Harbor by DNS name does not work when using Windows and WSL
# So for now we use localhost and custom port
externalURL: http://localhost:${harbor_port}
harborAdminPassword: "Harbor12345"

expose:
  type: nodePort
  nodePort:
    ports:
      http:
        port: ${harbor_port}
        nodePort: ${harbor_port}
  tls:
    enabled: false

internalTLS:
  enabled: false

persistence:
  enabled: true
  resourcePolicy: "delete"

trivy:
  enabled: false