apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: go-deploy-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: go-deploy-wildcard
  namespace: kube-system
spec:
  secretName: go-deploy-wildcard-secret
  secretTemplate:
    labels:
      app.kubernetes.io/deploy-name: deploy-wildcard-secret
  issuerRef: 
    kind: ClusterIssuer
    name: go-deploy-cluster-issuer
  commonName: ""
  dnsNames:
    - "*.deploy.localhost"
    - "*.apps.deploy.localhost"
    - "*.vm-app.deploy.localhost"
    - "*.storage.deploy.localhost"