---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`harbor.deploy.localhost`)
    kind: Rule
    services:
    - name: harbor-harbor-portal
      namespace: harbor
      port: 80
  - match: Host(`harbor.deploy.localhost`) && PathPrefix(`/api/`, `/service/`, `/v2/`, `/chartrepo/`, `/c/`)
    kind: Rule
    services:
    - name: harbor-harbor-core
      namespace: harbor
      port: 80
  tls:
    certResolver: default
    domains:
    - main: '*.harbor.deploy.localhost'
      sans:
      - 'harbor.deploy.localhost'