apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mongodb
  namespace: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
        volumeMounts:
        - name: vol-mongodb
          mountPath: /data/db
      volumes:
        - name: vol-mongodb
          persistentVolumeClaim:
            claimName: pvc-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: ${mongo_db_port}
  selector:
    app: mongodb
  type: NodePort