apiVersion: snapshot.storage.k8s.io/v1
driver: nfs.csi.k8s.io
kind: VolumeSnapshotClass
metadata:
  name: deploy-vm-snapshots
parameters:
  server: nfs-server.nfs-server.svc.cluster.local
  share: /mnt/nfs/snapshots
deletionPolicy: Delete