apiVersion: snapshot.storage.k8s.io/v1
driver: nfs.csi.k8s.io
kind: VolumeSnapshotClass
metadata:
  name: deploy-vm-snapshots
parameters:
  server: $nfs_server
  share: $nfs_share
deletionPolicy: Delete