name: ci-self-hosted

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"
        
