name: Generate artifacts

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"
