name: Generate build branch

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate build branch
      run: |
        git config --global user.name "kthcloud"
        git config --global user.email "noreply@cloud.cbh.kth.se"
        git config --global credential.helper cache

        git clone https://github.com/kthcloud/go-deploy -b build build
        
        cd scripts
        chmod +x ./generate-types.sh
        ./generate-types.sh
        chmod +x ./generate-docs.sh
        ./generate-docs.sh
        cd ..
        
        rm -rf build/docs
        rm -rf build/export

        cp -r docs build
        cp -r export build
        
        cd build
        git add docs
        git add export
        if ! git diff-index --quiet HEAD; then
          git commit -m "[🚚 Automatic] Generate build branch from main
          git push
        fi