name: Build, package, and publish NPM package

on:
  pull_request:
    branches:
      - main
    paths:
      - "export/**"
      - "dto/**"
      - ".github/workflows/npm-package.yml"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures tags are also fetched

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Bump NPM version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
        working-directory: ./export

      - name: Publish
        run: npm publish
        working-directory: ./export
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF}
          git add . && git commit -m "Bump npm package version" && git push origin HEAD:$BRANCH_NAME
